## Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => [1,2,3,4,5]      
Convert it into numpy array and print it

In [2]:
data = [1,2,3,4,5]
nparr1 = np.array(data)
nparr1

Make a python matrix (3x3) => [[1,2,3],[4,5,6],[7,8,9]]     
Convert it into numpy array and print it

In [3]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
nparr2 = np.array(matrix1)
nparr2

Make a matrix (3 x 3) using built-in methods (like arange(), reshape(), etc...)     
[[1,2,3],        
 [4,5,6],       
 [7,8,9]]

In [4]:
nparr3 = np.arange(1,18,2)
nparr3.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [5]:
nparr4 = np.random.rand(1,10)
nparr4 = nparr4 + nparr4
nparr4

array([[0.08245693, 1.11135267, 1.79360533, 1.13122523, 0.74780918,
        0.38027121, 1.12008231, 0.95798503, 1.76679482, 0.73379983]])

Create a numpy array => [1,2,3,4,5] and convert it to 2D matrix with 5 rows

In [6]:
nparr5 = np.array([1,2,3,4,5])
nparr5.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [7]:
nparr5.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [8]:
nparr6 = np.array([1,2,3,4,5,6,7,8,9,10])
print("The created array is", nparr6) 
print(" ")
# Accessing and printing the elements
print("The 3rd element is", nparr6[2])
print("The 4th element is", nparr6[3])
print("The 9th element is", nparr6[8])

The created array is [ 1  2  3  4  5  6  7  8  9 10]
 
The 3rd element is 3
The 4th element is 4
The 9th element is 9


Print alternate elements of that array

In [9]:
nparr6[0:10:2]

array([1, 3, 5, 7, 9])

In [10]:
nparr6[1:10:2]

array([ 2,  4,  6,  8, 10])

Change last three elements into 100 using broadcasting and print.

In [11]:
nparr6[-3:] = 100
nparr6

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 X 5 matrix (fill it with any element you like). Print it.    
Then print the middle (3 X 3) matrix.

In [12]:
matrix1 = np.arange(1,26).reshape(5,5)
matrix1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [13]:
matrix1[1:4, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])